### ISSUE TITLE
Clarification on run options of `ghimpact d3`

### ISSUE THREAD

**Issue by matthewfeickert** [henryiii/ghimpact#1]
@henryiii you made this image back on December 4th, 2020

![IrisConnections](https://user-images.githubusercontent.com/5142394/166627314-5cec88c5-fa03-4265-a5d8-5fcebd610277.png)

which Jim took and edited a bit today

![gihub-people-connections](https://user-images.githubusercontent.com/5142394/166627097-00cbf0d3-7880-49b7-a560-305bf75497bd.png)

It would be nice to try to update these figures with 2022 numbers. I assume that you made the figure originally with 

```console
$ poetry run ghimpact d3 
```

but from

```console
$ poetry run ghimpact d3 --help
Usage: ghimpact d3 [OPTIONS] [INPUT_FILES]...

  Convert a set of YAML file into a json file for d3

Options:
  --options FILENAME
  --output FILENAME
  --people / --no-people
  --help                  Show this message and exit.
```

it isn't immediately clear why the following fails.

```pytb
$ poetry run ghimpact d3 --output test.json matthewfeickert.yml henryiii.yml 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/feickert/Code/GitHub/IRIS-HEP/ghimpact/ghimpact/d3.py", line 21, in d3
    opts = yaml.safe_load(options)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/feickert/.pyenv/versions/3.10.3/envs/ghimpact-dev/lib/python3.10/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'NoneType' object has no attribute 'read'
```

I haven't gone and looked through the source code yet, but I thought I'd ask in the event that you remembered any key CLI options that I'm missing.

**Comment by jpivarski** [comment]
For the sake of the upcoming review, I made this:

![](https://raw.githubusercontent.com/jpivarski-talks/2022-03-04-reload-statistics/main/PLOTS/iris-hep-github-connections-for-report.svg)

The [notebook is here](https://github.com/jpivarski-talks/2022-03-04-reload-statistics/blob/main/iris-hep-github-connections.ipynb); it's based on "`involves:username`" searches with the GitHub API:

```bash
curl -s -u XXXXX:YYYYY "https://api.github.com/search/issues?q=involves:jpivarski&sort=created&order=desc&page=1&per_page=100"
```

That's different from actually committing code to a repo; it counts all of the comments that we make on each others' repos (like this one), but I think that's relevant because these interactions are what we want to address in the review. (Not just code, in the spirit of [all-contributors](https://allcontributors.org/).)

Since it's using the search API, it caps at 1000 results (whereas I have about 5000 results). Therefore, the "most recent" search is essential, and the plot represents the past couple of years for very talkative people, all time for everyone else.

It's a bipartite graph, but the usual layouts for bipartite graphs don't capture the clustering. General spring-optimized layouts don't capture the distinction between people and repos, and they tend to bunch up too much. That's why I ended up fixing the locations of the repos and let the people float around on springs. (I used networkx, not d3.) Now that the order of the repos is fixed, I had to set it appropriately, and mocked together something informal using Dijkstra distances and common sense. (That work is not represented in the Jupyter notebook.) I don't yet know of a good way to automate that.
